### ISSUE TITLE
NullPointerException TownyFlatFileSource

### ISSUE THREAD

**Issue by mixxit** [ElgarL/Towny#193]
```
[13:04:57 WARN]: [Towny] Plugin Towny v0.93.0.0 generated an exception while executing task 25

java.lang.NullPointerException: null

at com.palmergames.bukkit.towny.db.TownyFlatFileSource.lambda$initialize$0(TownyFlatFileSource.java:126) ~[?:?]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-98b862a]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-f56e2e7-98b862a]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by mixxit** [comment]
Also reported by missy on discord
