### ISSUE TITLE
Unable to claim plots

### ISSUE THREAD

**Issue by xSorch** [ElgarL/Towny#195]
[20:04:31] [Server thread/INFO]: [Town Msg] Atomia: NeutroniXimus put the plot (world,-72,245) up for sale!
[20:04:34] [Server thread/INFO]: Henario issued server command: /plot claim
[20:04:34] [Thread-35/WARN]: Exception in thread "Thread-35" 
[20:04:34] [Thread-35/WARN]: java.lang.IllegalStateException: AccountUpdateEvent cannot be triggered asynchronously from another thread.
[20:04:34] [Thread-35/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511)
[20:04:34] [Thread-35/WARN]: 	at com.iConomy.system.Holdings.math(Holdings.java:156)
[20:04:34] [Thread-35/WARN]: 	at com.iConomy.system.Holdings.add(Holdings.java:122)
[20:04:34] [Thread-35/WARN]: 	at com.iConomy.util.VaultConnector.depositPlayer(VaultConnector.java:104)
[20:04:34] [Thread-35/WARN]: 	at com.palmergames.bukkit.towny.TownyEconomyHandler.add(TownyEconomyHandler.java:299)
[20:04:34] [Thread-35/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject._pay(TownyEconomyObject.java:57)
[20:04:34] [Thread-35/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject._payTo(TownyEconomyObject.java:106)
[20:04:34] [Thread-35/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject.payTo(TownyEconomyObject.java:98)
[20:04:34] [Thread-35/WARN]: 	at com.palmergames.bukkit.towny.tasks.PlotClaim.residentClaim(PlotClaim.java:194)
[20:04:34] [Thread-35/WARN]: 	at com.palmergames.bukkit.towny.tasks.PlotClaim.run(PlotClaim.java:80)
[20:04:41] [Server thread/INFO]: Henario issued server command: /plot claim
[20:04:41] [Thread-36/WARN]: Exception in thread "Thread-36" 
[20:04:41] [Thread-36/WARN]: java.lang.IllegalStateException: AccountUpdateEvent cannot be triggered asynchronously from another thread.
[20:04:41] [Thread-36/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511)
[20:04:41] [Thread-36/WARN]: 	at com.iConomy.system.Holdings.math(Holdings.java:156)
[20:04:41] [Thread-36/WARN]: 	at com.iConomy.system.Holdings.add(Holdings.java:122)
[20:04:41] [Thread-36/WARN]: 	at com.iConomy.util.VaultConnector.depositPlayer(VaultConnector.java:104)
[20:04:41] [Thread-36/WARN]: 	at com.palmergames.bukkit.towny.TownyEconomyHandler.add(TownyEconomyHandler.java:299)
[20:04:41] [Thread-36/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject._pay(TownyEconomyObject.java:57)
[20:04:41] [Thread-36/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject._payTo(TownyEconomyObject.java:106)
[20:04:41] [Thread-36/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject.payTo(TownyEconomyObject.java:98)
[20:04:41] [Thread-36/WARN]: 	at com.palmergames.bukkit.towny.tasks.PlotClaim.residentClaim(PlotClaim.java:194)
[20:04:41] [Thread-36/WARN]: 	at com.palmergames.bukkit.towny.tasks.PlotClaim.run(PlotClaim.java:80)
[20:04:43] [Server thread/INFO]: Henario issued server command: /plot claim
[20:04:43] [Thread-37/WARN]: Exception in thread "Thread-37" 
[20:04:43] [Thread-37/WARN]: java.lang.IllegalStateException: AccountUpdateEvent cannot be triggered asynchronously from another thread.
[20:04:43] [Thread-37/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511)
[20:04:43] [Thread-37/WARN]: 	at com.iConomy.system.Holdings.math(Holdings.java:156)
[20:04:43] [Thread-37/WARN]: 	at com.iConomy.system.Holdings.add(Holdings.java:122)
[20:04:43] [Thread-37/WARN]: 	at com.iConomy.util.VaultConnector.depositPlayer(VaultConnector.java:104)
[20:04:43] [Thread-37/WARN]: 	at com.palmergames.bukkit.towny.TownyEconomyHandler.add(TownyEconomyHandler.java:299)
[20:04:43] [Thread-37/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject._pay(TownyEconomyObject.java:57)
[20:04:43] [Thread-37/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject._payTo(TownyEconomyObject.java:106)
[20:04:43] [Thread-37/WARN]: 	at com.palmergames.bukkit.towny.object.TownyEconomyObject.payTo(TownyEconomyObject.java:98)
[20:04:43] [Thread-37/WARN]: 	at com.palmergames.bukkit.towny.tasks.PlotClaim.residentClaim(PlotClaim.java:194)
[20:04:43] [Thread-37/WARN]: 	at com.palmergames.bukkit.towny.tasks.PlotClaim.run(PlotClaim.java:80)

**Comment by PantallazoAzul** [comment]
Same problem here, using iConomy :/
